// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpjlxjfcfyjjpzbsydue.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhwamx4amZjZnlqanB6YnN5ZHVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1Mzc4OTUsImV4cCI6MjA2MTExMzg5NX0.A8LlUMJVjsHrWi2P_DbHb3BbESTiM4DlxrbKpY3Xpl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);